[박지원] 검색 기능 추가
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #12
Opened 2021-09-07 06:49 UTC by jiwon5304

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-07 11:26 UTC, lordmyshepherd requested changes

2021-09-07 11:26 UTC, lordmyshepherd commented on products/views.py
> +class SearchView(View):
기존에 있는 product list view에 합쳐서 구현할 수 있는 방법은 없을까요?

2021-09-07 12:58 UTC, jiwon5304 commented
리스트 뷰 안에 검색 기능 추가해서 수정했습니다!!

2021-09-07 14:37 UTC, lordmyshepherd requested changes

2021-09-07 14:37 UTC, lordmyshepherd commented on products/views.py
> +                products = Product.objects.filter(type_id=type_id)
지원님 엔드포인트 잘 합쳐 주셨습니다!

추가로 피드백 더 드리자면, 하나의 엔드포인트에서 filter 그리고 search 기능을 유연하게 구현하려면 Q객체를 사용해서 구현해보세요~ 그리고 dictionary를 이용해서도 필터 기능을 구현해보시고, 각 방법에 장점과 단점은 무엇인지 고민해보시면 좋은 공부가 될 것 같습니다!

```suggestion
           q = Q()
           
            if search_keyword:
                q &= Q(name__icontains=search_keyword)
            if type_id:
               q &= Q(type_id=type_id)

            products = Product.objects.filter(q)
```

2021-09-08 08:45 UTC, jiwon5304 commented on products/views.py
> +                products = Product.objects.filter(type_id=type_id)
수정완료했습니다!

2021-09-08 09:12 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-08 09:12 UTC, merged