[하예준] Request merge on main from feature/cart
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #13
Opened 2021-09-07 07:47 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 Get 함수, 장바구니 갱신 Post 함수 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 상세 페이지에서 제품의 수량과 제품 삭제를 할 수 있는데, 이에 일일이 대응하는 함수를 만들지 않고,
주문하기 버튼을 눌렀을 때 장바구니 상품을 갱신하는 함수 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-07 09:35 UTC, TedJunny commented
기능으로 나누어서 PR 올렸습니다

2021-09-07 14:54 UTC, lordmyshepherd requested changes

2021-09-07 14:54 UTC, lordmyshepherd commented on orders/views.py
> +        )
몇 가지 피드백 남겨드려요!
1. `OrderItem`부터 접근하면 더 가독성이 좋아질 것 같습니다.
2. 추가로 prefetch_related()를 method를 사용하지 않아도 됩니다.
```suggestion
        carts = OrderItem.objects.filter(order__status_id=OrderStatus.Status.ON_CART.value)
```

3. cart의 총 가격을 계산하는 로직은 아래와 같이 `OrderItem` model에 속성으로 만들어서 사용할 수 있습니다.
4. 아래와 같이 수정하면 line 41 ~56 줄을 단 7줄로 줄일 수 있을 것 같네요~
```python
# order/models.py
class OrderItem(models.Model):
    ...
    @property
    def total_price(self):
        return self.product.price * self.quantity

# order/views.py
results = {
    "number_of_carts" : len(carts),
    "net_price"       : sum([product["total_price"] for product in result["products"]]),
    "carts"           : [{
        "product_name" : cart.product.name, 
        "total_price"  : cart.total_price
    } for cart in carts]
}
```

2021-09-08 00:40 UTC, TedJunny commented on orders/views.py
> +        )
"carts"           : [{
        "product_name" : cart.product.name, 
        "total_price"  : cart.total_price
    } for cart in carts]
    
    컴프리핸션이 실행되지 않은 상황에서 
    "net_price"       : sum([product["total_price"] for product in result["products"]]),을 먼저 입력해도 되나요?

2021-09-08 01:22 UTC, lordmyshepherd commented on orders/views.py
> +        )
위와 같이 net_price를 직접 할당해주려면 어떤 방법이 있을까요?

2021-09-08 04:12 UTC, TedJunny commented on orders/views.py
> +        )
오전에 코드 수정해서 올렸는데, 해당 방식은 어떤가요?

2021-09-08 06:23 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-08 06:24 UTC, merged