[하예준] : Request merge on main from feature/cart-renew
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #14
Opened 2021-09-07 09:39 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 Renew Post 함수 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 상세 페이지에서 제품의 수량과 제품 삭제를 할 수 있는데, 이에 일일이 대응하는 함수를 만들지 않고,
주문하기 버튼을 눌렀을 때 장바구니 상품을 갱신하는 함수 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-07 15:13 UTC, lordmyshepherd requested changes

2021-09-07 15:13 UTC, lordmyshepherd commented on orders/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
1. 비회원이 주문하는 경우 장바구니 상태를 Frontend 단에서 관리하다가 주문시에 로그인하도록 만들어주면, 위와 같은 로직을 사용해서 처리할 수 있을 것 같은데 어떠신가요? (정상적으로는 비회원일때는 장바구니 테이블에 데이터를 쌓지 않습니다.)

2. 회원이 주문하는 경우
  - 순서 : 장바구니 -> 주문 
  - 로그인한 회원이 주문하는 경우이므로 
```python
   data = [
   {
        "produc_id" : 1,
        "quantity" : 10
    }, 
   {
        "produc_id" : 5,
        "quantity" : 10
    }
   ]
```

아래와 같은 방향성을 가지고 리펙토링 해보면 코드를 줄일 수 있을 것 같네요.
```python
    order = Order.objects.filter(status_id=OrderStatus.Status.ON_CART.value, user=request.user)
    order_items = order.orderitem_set.all()

    for cart in data["carts"]:
        cart = OrderItem.objects.get_or_create(product_id=..)

```

2021-09-08 06:35 UTC, lordmyshepherd requested changes

2021-09-08 06:35 UTC, lordmyshepherd commented on orders/views.py
> +                ).delete()
```suggestion
    order = Order.objects.filter(status_id=OrderStatus.Status.ON_CART.value, user=request.user)

    order.orderitems.all().delete()
    
    for cart in carts:
        OrderItem.objects.create(product_id=cart["product_id"], quantity=cart["quantity"], )
        
    order.status_id = OrderStatus.Status.COMPLETED.value
    
```

2021-09-08 07:39 UTC, TedJunny commented
@lordmyshepherd 수정했습니다!! 혹시 남기신 말씀의 의미가 on_delete 옵션을 고려하라고 하신 것이 맞나요?? 정확히 파악하지 못했는데 정답을 알려주시면 감사하겠습니다!!

2021-09-08 11:42 UTC, TedJunny commented
transaction 사용했습니다!!

2021-09-09 01:31 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-09 01:31 UTC, merged