[하예준] : Reqeust merge on main from feature/order-information
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #15
Opened 2021-09-07 10:59 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 주문 정보 업데이트 함수 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 주문하기 전에 배송과 관련한 정보를 저장하는 함수 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-08 07:45 UTC, TedJunny commented
수정한 부분 커밋했습니다!

2021-09-09 01:32 UTC, lordmyshepherd requested changes

2021-09-09 01:32 UTC, lordmyshepherd commented on orders/views.py
> +            )
user 검색 조건이 빠진 것 같네요??

2021-09-09 01:41 UTC, TedJunny commented on orders/views.py
> +            )
네 이부분 수정해서 다시 올리겠습니다!

2021-09-09 06:30 UTC, kst6294 requested changes

2021-09-09 06:30 UTC, kst6294 commented on orders/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
`PATCH 8000/order `
`PATCH 8000/order-information` 

위 두 방식에 차이가 있나요?

2021-09-09 06:42 UTC, TedJunny commented on orders/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
@kst6294 장바구니에서 주문까지의 플로우에서 PATCH 8000/order은 장바구니의 정보를 주문으로 확정하는 과정의 엔드포인트이고 ,
PATCH 8000/order-information은 결제 전에 배송관련 정보를 넣는 플로우의 엔드포인트입니다!

2021-09-09 07:20 UTC, TedJunny commented
@kst6294 수정했습니다!!

2021-09-09 07:37 UTC, kst6294 approved these changes

2021-09-09 07:37 UTC, merged