[하예준] Request merge on main from feature/cart-delete
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #18
Opened 2021-09-08 09:32 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 상품 Delete 함수 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 상태 확인 후, 장바구니 상품을 삭제하는 함수

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-08 09:48 UTC, lordmyshepherd requested changes

2021-09-08 09:48 UTC, lordmyshepherd commented on orders/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
REST API에서 DELETE를 구현할 때에는 path parameter를 사용해서 구현해야 합니다!
`DELETE /cart/1` 1번 카트를 지워라!

```suggestion
    @login_decorator
    def delete(self, request, cart_id):
        try:
            OrderItem.objects.get(product_id=product_id, ..).delete()

            return JsonResponse(
                {"message": f"PRODUCT {data['product_id']} DELETED"}, status=200
            )
        except KeyError:
            return JsonResponse({"message": "KEY_ERROR"}, status=400)
```

2021-09-08 12:12 UTC, TedJunny commented
Path Variable을 사용하여 삭제할 수 있도록 수정했습니다!!

2021-09-09 06:31 UTC, kst6294 approved these changes

2021-09-09 06:31 UTC, merged