[주종민, 박지원, 하예준] Add : 모델링 클래스 생성
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #2
Opened 2021-08-31 11:50 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 고객, 제품, 구매 앱 모델 클래스 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- ERD 데이터베이스 모델링을 기반해서 클래스 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-31 12:36 UTC, lordmyshepherd requested changes

2021-08-31 12:36 UTC, lordmyshepherd commented on .vscode/settings.json
> +{
vscode file은 올라오지 않도록 gitignore에 추가해주세요~
수정해주신 후에 마지막에 `Files changed`를 눌러서 변경사항이 제대로 반영 되었는지 확인해주세요~

2021-08-31 12:36 UTC, lordmyshepherd commented on orders/models.py
> +        db_table = "order_products"
주문 상품은 `OrderItem`이라는 용어를 많이 사용합니다~

```suggestion
class OrderItem(models.Model):
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE)
    quantity = models.SmallIntegerField()
    order = models.ForeignKey("Order", on_delete=models.CASCADE)
    status = models.ForeignKey("OrderItemStatus", on_delete=models.CASCADE)

    class Meta:
        db_table = "order_products"
```

2021-08-31 12:36 UTC, lordmyshepherd commented on products/models.py
> +class Product(models.Model):
데이터의 이력 관리를 위해서 대부분의 테이블에 `created_at`, `updated_at` column을 추가해주세요!

2021-08-31 12:36 UTC, lordmyshepherd commented on products/models.py
> +    sizes = models.ManyToManyField("Size", related_name="products")
`ManyToManyField`는 `through=` option을 사용해서 직접 중간테이블을 구현해주세요!

![image](https://user-images.githubusercontent.com/53214510/131503613-60319337-6998-4ab8-9438-f1a7c95fcaf6.png)

[참고] https://docs.djangoproject.com/en/3.2/topics/db/models/#intermediary-manytomany

2021-09-01 00:19 UTC, TedJunny commented on .vscode/settings.json
> +{
수정했습니다!

2021-09-01 00:23 UTC, TedJunny commented on orders/models.py
> +        db_table = "order_products"
수정했습니다.

2021-09-01 00:35 UTC, TedJunny commented on products/models.py
> +    sizes = models.ManyToManyField("Size", related_name="products")
수정했습니다

2021-09-01 00:43 UTC, TedJunny commented on products/models.py
> +class Product(models.Model):
모델링 리뷰 받을 때 해당 부분에 대한 가이드는 없어서 생각 못했었습니다! 일단 데이터 이력관리가 필요하다고 판단한 Product 클래스와  Order 앱 관련 클래스들에 추가하는 것으로 수정했습니다!! 

질문 있습니다!

1. 데이터 이력관리가 필요한지 어떻게 결정하고 필드를 추가해야 하나요?
2. 현재 Order앱에 대부분의 클래스에 추가했는데 데이터 이력관리에 대한 코드 재사용성을 향상 시킬 방법이 있을까요?

2021-09-01 01:42 UTC, lordmyshepherd commented on products/models.py
> +class Product(models.Model):
정말 좋은 질문이에요!!
1. 이력관리가 필요한 경우는 도메인(예를들면, e-커머스, 핀테크...)마다 다르겠지만 보통은 중요하고 자주 생성되고 업데이트 되는 데이터를 기준으로 결정하시면 됩니다.
예를 들어 e-커머스에서 주문 데이터는 굉장히 중요한 데이터입니다. 그렇기때문에 주문이 언제 생성 되었으며, 언제 수량이 변경 되었는지 등에 대한 정보를 기록해야 되는 것이죠. 나중에 만약에 주문이 누군가의 실수로 잘 못 수정된 경우 updated된 시점을 기준으로 데이터 디버깅을 하는데 사용할 수도 있겠죠.

2. class의 inheritance(상속) 개념을 이용해서 재사용성을 향상시켜보시면 어떨까요?

2021-09-01 02:56 UTC, TedJunny commented on products/models.py
> +class Product(models.Model):
추상 클래스 상속을 이용해서 재사용성 향상 시키드록 수정했습니다!

2021-09-01 03:35 UTC, lordmyshepherd commented
LGTM 👍

2021-09-01 03:39 UTC, merged