[하예준] Add: 제품 상세 페이지 Get API 구현
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #5
Opened 2021-09-01 12:24 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 제품 상세 페이지 Get API 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

![스크린샷 2021-09-01 오후 9 23 28](https://user-images.githubusercontent.com/65930935/131670509-fce9923d-332b-4e1a-a86e-08ad67f5dae1.png)

2021-09-02 05:27 UTC, lordmyshepherd requested changes

2021-09-02 05:27 UTC, lordmyshepherd commented on products/urls.py
> +    path("/list", views.ProductListView.as_view()),
URI를 정말 잘 만들어주셨네요!! 👍

2021-09-02 05:27 UTC, lordmyshepherd commented on products/views.py
> +        images = Image.objects.filter(product=product.id)
line 11~ line 14를 한줄로 줄여 주시고,  `images = Image.objects.filter(product=product.id)` 코드를 Product 부터 접근해서 가져오도록 수정해주세요~

```suggestion
        product = Product.objects.get(id=kwargs["product_id"])
        colors = product.colors.all()
        sizes = product.sizes.all()
        images = Image.objects.filter(product=product.id)
```

2021-09-02 05:27 UTC, lordmyshepherd commented on products/views.py
> +        )
이 부분은 `list comprehension` 표현식을 사용해서 구현하시면 코드도 짧아지고, 속도도 빨라질 수 있습니다~ 적용해보세요!

2021-09-02 05:32 UTC, TedJunny commented on products/urls.py
> +    path("/list", views.ProductListView.as_view()),
감사합니다!

2021-09-02 05:34 UTC, TedJunny commented
@lordmyshepherd views.py의 두 리뷰 내용이 조금 이해가 되지 않는데 혹시 오늘 로비에서 리뷰를 받아보아도 괜찮을까요??

2021-09-02 06:53 UTC, TedJunny commented on products/views.py
> +        images = Image.objects.filter(product=product.id)
수정했습니다!

2021-09-02 06:53 UTC, TedJunny commented on products/views.py
> +        )
네 아까 같이 확인했습니다!

2021-09-02 09:58 UTC, TedJunny commented
@lordmyshepherd 수정사항 반영해서 다시 커밋했습니다!

2021-09-03 01:27 UTC, lordmyshepherd commented on products/views.py
> +        result = {}
```suggestion
```

2021-09-03 01:27 UTC, lordmyshepherd commented on products/views.py
> +class ProductListView(View):
```suggestion
```

2021-09-03 01:27 UTC, lordmyshepherd commented on products/views.py
> +        result = {}
아직 여기에 result가 남았네요??

line 11번 지워주실 수 있나요?

2021-09-03 01:45 UTC, TedJunny commented
@lordmyshepherd 네 다시 올렸습니다!!

2021-09-03 01:59 UTC, lordmyshepherd commented
예준님 고생 많으셨습니다~
LGTM 👍

2021-09-03 01:59 UTC, merged