[하예준] Request merge on main from feature/order_product
wecode-bootcamp-korea/24-1st-LaFesta-backend pull request #9
Opened 2021-09-04 08:16 UTC by TedJunny

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-  장바구니 Post Method 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 제품 상세 페이지에서 쇼핑백에 추가 버튼을 눌렀을 때 호출하게 되는 Post 함수 추가
- request.body에서 product_id를 받아서 해당 제품에 대한 로직을 처리
- 제품에 대한 정보가 테이블에 존재하는지 아닌지에 따른 각기 다른 처리를 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Post 함수인데, 로직 과정에서 Update 기능을 수행하는 것이 있는데 이것이 REST API에 어긋나는지 궁금합니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-06 04:35 UTC, lordmyshepherd requested changes

2021-09-06 04:35 UTC, lordmyshepherd commented on orders/views.py
> +                if order_item.order.status.status=="OC":
"OC"가 뭔가요??

2021-09-06 04:35 UTC, lordmyshepherd commented on orders/views.py
> +        default_item_status_id = OrderItemStatus.objects.get(status="DE").id
"DE"는 뭔가요?

2021-09-06 04:36 UTC, TedJunny commented on orders/views.py
> +                if order_item.order.status.status=="OC":
On Cart의 줄임말입니다!

2021-09-06 04:36 UTC, TedJunny commented on orders/views.py
> +        default_item_status_id = OrderItemStatus.objects.get(status="DE").id
Default의 줄임말 입니다!

2021-09-06 05:02 UTC, TedJunny commented
@lordmyshepherd choice 옵션을 부여하는 것처럼 줄임말 표현을 사용하고 싶었는데 그냥 풀어서 하는 걸로 바꾸어야 하나요??
예를 들어 유저의 성별은 M, F로 저장하고 있습니다!

2021-09-06 06:17 UTC, TedJunny commented
혹시 PR 템플릿의 질문에도 답변을 해주신다면 너무 도움이 될 것 같습니다!

2021-09-06 11:13 UTC, TedJunny commented
오늘 코드리뷰 해주신 부분 반영해서 수정했고, 모든 케이스에서 작동하는 것 확인했습니다!! 병민님 혹시 제 pr 템플릿에 있는 질문에도 답변 코멘트 남겨주시면 더 좋은 백엔더가 될 수 있을 것 같습니다!!

2021-09-07 01:12 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-07 01:13 UTC, merged